run: test
  go run .

test:
  go fmt ./...
  revive -formatter friendly -set_exit_status ./...
  go vet ./...
  go test -coverprofile=coverage.out ./...

build:
  go build -ldflags "-s -w" # Remove symbol and debug info for smallest binary
